[build]
command = "./mvnw -DskipTests package"

[start]
command = "java -Dserver.port=$PORT -jar target/*.jar"

[variables]
JAVA_VERSION = "21"
SPRING_DATASOURCE_URL = "jdbc:postgresql://postgres.railway.internal:5432/railway?user=postgres&password=YuYlEQFTDGXFBBqatcFaJirvGCKeLvtg"
